name: Test FastAPI Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-uvicorn:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install fastapi uvicorn

      - name: Start Uvicorn
        run: |
          source venv/bin/activate
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 5

      - name: Test if localhost:8000 is reachable
        run: |
          curl --fail http://127.0.0.1:8000/ || exit 1
